<?php

require_once '/home/naokimiyasaka/public_html/mvc_board/php/Bbs.php';

/**
 * Test class for Bbs.
 * Generated by PHPUnit on 2012-08-27 at 14:06:33.
 */
class BbsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Bbs
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Bbs;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Bbs::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct()
    {
        $this->assertTrue($this->object->__destruct());
    }

    /**
     * @covers Bbs::runBoot
     * @todo Implement testRunBoot().
     */
    public function testRunBoot()
    {
        //メソットチェック 正しい
        $this->assertEquals( $this->object->runBoot('DispMain', 'dispPage'), Bbs::SUCCESS );

        //メソットチェック クラスだけおかしい
        $this->assertEquals( $this->object->runBoot('hoho', 'dispPage'), Bbs::FILE_CHECK_ERR );

        //メソットチェック　メソットだけおかしい
        $this->assertEquals( $this->object->runBoot('DispMain', 'hoge'), Bbs::FILE_METHOD_ERR );
    }

    /**
     * @covers Bbs::mainRun
     * @todo Implement testMainRun().
     */
    public function testMainRun()
    {
        //失敗
        $_GET['class'] = 'DispMain';
        $_GET['method'] = 'hoge';
        $this->assertFalse( $this->object->mainRun());

        //成功
        $_GET['class'] = 'DispMain';
        $_GET['method'] = 'dispPage';
        $this->assertTrue( $this->object->mainRun());
    }
}
?>
