<?php

require_once '/home/naokimiyasaka/public_html/mvc_board/php/Uitl.php';

/**
 * Test class for Uitl.
 * Generated by PHPUnit on 2012-08-27 at 14:08:32.
 */
class UitlTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Uitl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Uitl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Uitl::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct()
    {
        $this->assertTrue($this->object->__destruct());
    }

    /**
     * @covers Uitl::getPost
     * @todo Implement testGetPost().
     */
    public function testGetPost()
    {
        $this->assertNull($this->object->getPost('hoge'));
        $_POST['boardid'] = 20;
        $this->assertEquals(20, $this->object->getPost('boardid'));
    }

    /**
     * @covers Uitl::getGet
     * @todo Implement testGetGet().
     */
    public function testGetGet()
    {
        $this->assertNull($this->object->getGet('hoge'));
        $_GET['boardid'] = 20;
        $this->assertEquals(20, $this->object->getGet('boardid'));
    }

    public function testredirect()
    {
    }
}
?>
