<?php

require_once '/home/naokimiyasaka/public_html/mvc_board/php/DispMain.php';
//エラーが発生した場合にエラー表示をする設定
ini_set('display_errors', 1);
//Smartyインストールディレクトリを定数定義
define('SMARTY_DIR', '../smarty/libs/');
//Smartyを使うための準備
require_once SMARTY_DIR . 'Smarty.class.php';
require_once './DbAccess.php';
require_once './Uitl.php';
require_once './Logic.php';

/**
 * Test class for DispMain.
 * Generated by PHPUnit on 2012-08-27 at 14:08:05.
 */
class DispMainTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DispMain
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $db = new DbAccess();
        $this->object = new DispMain($db);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DispMain::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct()
    {
        $this->assertTrue( $this->object->__destruct() );
    }

    /**
     * @covers DispMain::dispPage
     * @todo Implement testDispPage().
     */
    public function testDispPage()
    {
        $this->_smarty = new Smarty();
        $this->_smarty->caching = 0;
        $this->_smarty->template_dir = '../templates/';
        $this->_smarty->compile_dir  = '../templates_c/';
        $this->_smarty->config_dir   = '../configs/';
        $this->_smarty->cache_dir    = '../cache/';
        $this->assertTrue( $this->object->dispPage($this->_smarty) );
    }
}
?>
