<?php

require_once '/home/naokimiyasaka/public_html/mvc_board/php/Edit.php';
//エラーが発生した場合にエラー表示をする設定
ini_set('display_errors', 1);
//Smartyインストールディレクトリを定数定義
define('SMARTY_DIR', '../smarty/libs/');
//Smartyを使うための準備
require_once SMARTY_DIR . 'Smarty.class.php';
require_once './DbAccess.php';
require_once './Uitl.php';
require_once './Logic.php';

/**
 * Test class for Edit.
 * Generated by PHPUnit on 2012-08-27 at 14:08:12.
 */
class EditTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Edit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $db = new DbAccess();
        $this->object = new Edit($db);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Edit::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct()
    {
        $this->assertTrue( $this->object->__destruct() );
    }


    public function testGetDb()
    {
        $this->assertNotNull( $this->object->getDb() );
    }

    /**
     * @covers Edit::dispPage
     * @todo Implement testDispPage().
     */
    public function testDispPage()
    {
        $url = "./index.php";
        runkit_method_redefine('Uitl', 'redirect', '$url', 'return true;', RUNKIT_ACC_PUBLIC);
        $smarty = new Smarty();
        $smarty->caching = 0;
        $smarty->template_dir = '../templates/';
        $smarty->compile_dir  = '../templates_c/';
        $smarty->config_dir   = '../configs/';
        $smarty->cache_dir    = '../cache/';

        //失敗
        $this->assertFalse( $this->object->dispPage($smarty) );

        //取得
        $res = mysql_query("select * from BOARD");
        $data = $this->object->getDb()->getSqlContents($res);
        $_GET['id'] = $data['boardid'];
        $this->assertTrue( $this->object->dispPage($smarty) );

        //失敗
        $res = mysql_query("select * from BOARD");
        $data = $this->object->getDb()->getSqlContents($res);
        $_GET['id'] = $data['boardid'];
        $_POST['send'] = 'send';
        $this->assertTrue( $this->object->dispPage($smarty) );
    }
}
?>
