<?php

require_once '/home/naokimiyasaka/public_html/BbsLoginHM_Miya/php/Login.php';

require_once '/home/naokimiyasaka/public_html/mvc_board/php/Details.php';
//エラーが発生した場合にエラー表示をする設定
ini_set('display_errors', 1);
//Smartyインストールディレクトリを定数定義
define('SMARTY_DIR', '../smarty/libs/');
//Smartyを使うための準備
require_once SMARTY_DIR . 'Smarty.class.php';
require_once './DbAccess.php';
require_once './Uitl.php';
require_once './Logic.php';

/**
 * Test class for Login.
 * Generated by PHPUnit on 2012-11-13 at 14:10:47.
 */
class LoginTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Login
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $db = new DbAccess();
        $this->object = new Login($db);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Login::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Login::getDb
     * @todo Implement testGetDb().
     */
    public function testGetDb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Login::dispPage
     * @todo Implement testDispPage().
     */
    public function testDispPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
